// Hand-curated, progressively-filled content for the fields REST-style datasets
// don't cover well: notable landmarks, brands, rivers, mountains, major cities,
// and states/provinces. Keyed by ISO 3166-1 alpha-3 code.
//
// Intentionally NOT exhaustive — only well-established, low-risk-of-error facts
// for a subset of high-traffic countries are included here. Every other country
// simply renders an empty array and the UI shows "not added yet" rather than
// guessing. Extend this file over time (see README "Phase 2 content").

export const CURATED = {
  USA: {
    majorCities: ['New York City', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    landmarks: ['Statue of Liberty', 'Grand Canyon', 'Golden Gate Bridge'],
    brands: ['Apple', 'Coca-Cola', 'Nike'],
    rivers: ['Mississippi River', 'Colorado River'],
    mountains: ['Denali', 'Mount Whitney'],
    provinces: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
  },
  CAN: {
    majorCities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary'],
    landmarks: ['Niagara Falls', 'CN Tower'],
    brands: ['Tim Hortons', 'Shopify', 'Canada Goose'],
    rivers: ['Saint Lawrence River', 'Mackenzie River'],
    mountains: ['Mount Logan'],
    provinces: ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Nova Scotia', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Northwest Territories', 'Nunavut', 'Yukon'],
  },
  MEX: {
    majorCities: ['Guadalajara', 'Monterrey', 'Puebla', 'Tijuana'],
    landmarks: ['Chichen Itza', 'Teotihuacan'],
    brands: ['Corona', 'Bimbo'],
    rivers: ['Rio Grande', 'Rio Balsas'],
    mountains: ['Pico de Orizaba', 'Popocatepetl'],
  },
  BRA: {
    majorCities: ['Sao Paulo', 'Rio de Janeiro', 'Salvador', 'Fortaleza'],
    landmarks: ['Christ the Redeemer', 'Iguazu Falls'],
    brands: ['Havaianas', 'Embraer'],
    rivers: ['Amazon River', 'Sao Francisco River'],
    mountains: ['Pico da Neblina'],
  },
  ARG: {
    majorCities: ['Cordoba', 'Rosario', 'Mendoza'],
    landmarks: ['Perito Moreno Glacier', 'Iguazu Falls'],
    brands: ['Arcor'],
    rivers: ['Parana River', 'Rio de la Plata'],
    mountains: ['Aconcagua'],
  },
  GBR: {
    majorCities: ['Birmingham', 'Manchester', 'Glasgow', 'Liverpool'],
    landmarks: ['Big Ben', 'Stonehenge', 'Tower Bridge'],
    brands: ['BP', 'HSBC', 'Burberry'],
    rivers: ['River Thames', 'River Severn'],
    mountains: ['Ben Nevis'],
    provinces: ['England', 'Scotland', 'Wales', 'Northern Ireland'],
  },
  FRA: {
    majorCities: ['Marseille', 'Lyon', 'Toulouse', 'Nice'],
    landmarks: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral'],
    brands: ["L'Oreal", 'LVMH', 'Renault'],
    rivers: ['Seine', 'Loire', 'Rhone'],
    mountains: ['Mont Blanc'],
  },
  DEU: {
    majorCities: ['Hamburg', 'Munich', 'Cologne', 'Frankfurt'],
    landmarks: ['Brandenburg Gate', 'Neuschwanstein Castle', 'Cologne Cathedral'],
    brands: ['Volkswagen', 'Siemens', 'Adidas', 'BMW'],
    rivers: ['Rhine', 'Elbe', 'Danube'],
    mountains: ['Zugspitze'],
    provinces: ['Baden-Wurttemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hesse', 'Lower Saxony', 'Mecklenburg-Vorpommern', 'North Rhine-Westphalia', 'Rhineland-Palatinate', 'Saarland', 'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia'],
  },
  ITA: {
    majorCities: ['Milan', 'Naples', 'Turin', 'Florence'],
    landmarks: ['Colosseum', 'Leaning Tower of Pisa', 'Venice Canals'],
    brands: ['Ferrari', 'Gucci', 'Fiat'],
    rivers: ['Po River', 'Tiber'],
    mountains: ['Mont Blanc (shared)', 'Gran Paradiso'],
  },
  ESP: {
    majorCities: ['Barcelona', 'Valencia', 'Seville'],
    landmarks: ['Sagrada Familia', 'Alhambra'],
    brands: ['Zara', 'Santander'],
    rivers: ['Ebro', 'Tagus'],
    mountains: ['Teide', 'Mulhacen'],
  },
  PRT: {
    majorCities: ['Porto', 'Braga'],
    landmarks: ['Belem Tower', 'Jeronimos Monastery'],
    brands: ['TAP Air Portugal'],
    rivers: ['Tagus', 'Douro'],
  },
  NLD: {
    majorCities: ['Rotterdam', 'The Hague', 'Utrecht'],
    landmarks: ['Anne Frank House', 'Windmills of Kinderdijk'],
    brands: ['Philips', 'Heineken', 'ASML'],
    rivers: ['Rhine', 'Meuse'],
  },
  BEL: {
    majorCities: ['Antwerp', 'Ghent'],
    landmarks: ['Atomium', 'Grand Place'],
    brands: ['AB InBev'],
    rivers: ['Scheldt', 'Meuse'],
  },
  CHE: {
    majorCities: ['Zurich', 'Geneva', 'Basel'],
    landmarks: ['Matterhorn', 'Chateau de Chillon'],
    brands: ['Nestle', 'Rolex', 'UBS'],
    rivers: ['Rhine', 'Rhone'],
    mountains: ['Matterhorn', 'Monte Rosa'],
  },
  AUT: {
    majorCities: ['Graz', 'Salzburg'],
    landmarks: ['Schonbrunn Palace', 'Hallstatt'],
    brands: ['Red Bull', 'Swarovski'],
    rivers: ['Danube'],
    mountains: ['Grossglockner'],
  },
  POL: {
    majorCities: ['Krakow', 'Lodz', 'Wroclaw'],
    landmarks: ['Wawel Castle', 'Auschwitz-Birkenau Memorial'],
    brands: ['LOT Polish Airlines'],
    rivers: ['Vistula', 'Oder'],
  },
  SWE: {
    majorCities: ['Gothenburg', 'Malmo'],
    landmarks: ['Vasa Museum'],
    brands: ['IKEA', 'H&M', 'Volvo', 'Spotify', 'Ericsson'],
    rivers: ['Klaralven'],
    mountains: ['Kebnekaise'],
  },
  NOR: {
    majorCities: ['Bergen', 'Trondheim'],
    landmarks: ['Geirangerfjord', 'Preikestolen'],
    brands: ['Equinor'],
    rivers: ['Glomma'],
    mountains: ['Galdhopiggen'],
  },
  FIN: {
    majorCities: ['Tampere', 'Turku'],
    landmarks: ['Suomenlinna'],
    brands: ['Nokia'],
    rivers: ['Kemijoki'],
    mountains: ['Halti'],
  },
  DNK: {
    majorCities: ['Aarhus', 'Odense'],
    landmarks: ['The Little Mermaid statue', 'Tivoli Gardens'],
    brands: ['LEGO', 'Maersk', 'Carlsberg'],
    rivers: ['Gudena'],
  },
  RUS: {
    majorCities: ['Saint Petersburg', 'Novosibirsk', 'Yekaterinburg'],
    landmarks: ['Red Square', "Saint Basil's Cathedral"],
    brands: ['Gazprom', 'Kaspersky'],
    rivers: ['Volga', 'Ob', 'Yenisei', 'Lena'],
    mountains: ['Mount Elbrus'],
  },
  UKR: {
    majorCities: ['Kharkiv', 'Odesa', 'Lviv'],
    landmarks: ['Saint Sophia Cathedral'],
    rivers: ['Dnipro River'],
    mountains: ['Hoverla'],
  },
  TUR: {
    majorCities: ['Istanbul', 'Izmir'],
    landmarks: ['Hagia Sophia', 'Cappadocia'],
    brands: ['Turkish Airlines'],
    rivers: ['Euphrates', 'Tigris'],
    mountains: ['Mount Ararat'],
  },
  GRC: {
    majorCities: ['Thessaloniki'],
    landmarks: ['Acropolis of Athens', 'Parthenon'],
    rivers: ['Aliakmon'],
    mountains: ['Mount Olympus'],
  },
  EGY: {
    majorCities: ['Alexandria', 'Giza'],
    landmarks: ['Pyramids of Giza', 'Great Sphinx of Giza'],
    rivers: ['Nile River'],
  },
  MAR: {
    majorCities: ['Casablanca', 'Marrakesh', 'Fez'],
    landmarks: ['Hassan II Mosque', 'Jemaa el-Fnaa'],
    mountains: ['Jebel Toubkal (Atlas Mountains)'],
  },
  NGA: {
    majorCities: ['Lagos', 'Kano', 'Ibadan'],
    landmarks: ['Zuma Rock'],
    brands: ['Dangote Group'],
    rivers: ['Niger River'],
  },
  KEN: {
    majorCities: ['Mombasa', 'Kisumu'],
    landmarks: ['Maasai Mara National Reserve'],
    mountains: ['Mount Kenya'],
    rivers: ['Tana River'],
  },
  ZAF: {
    majorCities: ['Johannesburg', 'Cape Town', 'Durban'],
    landmarks: ['Table Mountain', 'Kruger National Park'],
    mountains: ['Table Mountain'],
    rivers: ['Orange River'],
  },
  IND: {
    majorCities: ['Mumbai', 'Bangalore', 'Kolkata', 'Chennai'],
    landmarks: ['Taj Mahal', 'Red Fort'],
    brands: ['Tata', 'Reliance', 'Infosys'],
    rivers: ['Ganges', 'Brahmaputra', 'Yamuna'],
    mountains: ['Kangchenjunga'],
    provinces: ['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
  },
  CHN: {
    majorCities: ['Shanghai', 'Guangzhou', 'Shenzhen', 'Chongqing'],
    landmarks: ['Great Wall of China', 'Forbidden City', 'Terracotta Army'],
    brands: ['Huawei', 'Alibaba', 'Xiaomi'],
    rivers: ['Yangtze River', 'Yellow River'],
    mountains: ['Mount Everest (shared)'],
  },
  JPN: {
    majorCities: ['Osaka', 'Yokohama', 'Nagoya'],
    landmarks: ['Mount Fuji', 'Fushimi Inari Shrine'],
    brands: ['Toyota', 'Sony', 'Nintendo', 'Honda'],
    rivers: ['Shinano River'],
    mountains: ['Mount Fuji'],
  },
  KOR: {
    majorCities: ['Busan', 'Incheon'],
    landmarks: ['Gyeongbokgung Palace'],
    brands: ['Samsung', 'Hyundai', 'LG'],
    rivers: ['Han River'],
    mountains: ['Hallasan'],
  },
  IDN: {
    majorCities: ['Surabaya', 'Bandung', 'Medan'],
    landmarks: ['Borobudur', 'Bali temples'],
    rivers: ['Kapuas River'],
    mountains: ['Puncak Jaya'],
  },
  THA: {
    majorCities: ['Chiang Mai', 'Phuket'],
    landmarks: ['Grand Palace', 'Wat Arun'],
    rivers: ['Chao Phraya'],
    mountains: ['Doi Inthanon'],
  },
  VNM: {
    majorCities: ['Ho Chi Minh City', 'Da Nang'],
    landmarks: ['Ha Long Bay'],
    rivers: ['Mekong River', 'Red River'],
  },
  PHL: {
    majorCities: ['Quezon City', 'Cebu City', 'Davao'],
    landmarks: ['Chocolate Hills'],
    mountains: ['Mount Apo'],
  },
  AUS: {
    majorCities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
    landmarks: ['Sydney Opera House', 'Uluru', 'Great Barrier Reef'],
    brands: ['Qantas', 'Woolworths'],
    rivers: ['Murray River'],
    mountains: ['Mount Kosciuszko'],
    provinces: ['New South Wales', 'Victoria', 'Queensland', 'Western Australia', 'South Australia', 'Tasmania', 'Australian Capital Territory', 'Northern Territory'],
  },
  NZL: {
    majorCities: ['Auckland', 'Christchurch'],
    landmarks: ['Milford Sound', 'Hobbiton Movie Set'],
    brands: ['Fonterra'],
    mountains: ['Aoraki / Mount Cook'],
  },
  SAU: {
    majorCities: ['Jeddah', 'Mecca', 'Medina'],
    landmarks: ['Masjid al-Haram'],
    brands: ['Saudi Aramco'],
  },
  ARE: {
    majorCities: ['Dubai', 'Sharjah'],
    landmarks: ['Burj Khalifa', 'Burj Al Arab', 'Palm Jumeirah'],
    brands: ['Emirates', 'Etihad Airways'],
  },
};
